////////////////////////////////////////////////////////////
//
//    Библиотека
//    Copyright © 2022-2023 Љубомир Мићић
//    Сва права су заштићена.
//
////////////////////////////////////////////////////////////

using System;
using STR = System.String;
using RECNIK = System.Collections.Generic.Dictionary<string, string>;

namespace Project {
    public static class UDK {
        public enum UDK_Koriscenje {
            Nista,
            Osnovno,
            Sve
        }

        public static readonly RECNIK UDK_Lista = new RECNIK() {
            {"0", "Opsta grupa"},
            {"001", "Nauka i znanje uopšte"},
            {"001.8", "Metodologija. Tehnički i naučni postupci istraživanja"},
            {"001.89", "Organizacija nauke i naučnog rada"},
            {"001.891", "Naučna istraživanja. Metode ispitivanja"},
            {"001.895", "Inovacije"},
            {"002", "Dokumentacija (skupljanje, sortiranje, uređivanje)"},
            {"002.6", "Centri za dokumentaciju"},
            {"003", "Sistemi pisanja i pisma. Znaci i simboli. Šifre. Grafičko predstavljanje"},
            {"003.3", "Pojedina pisma"},
            {"004", "Računarska nauka i tehnologija. Računarstvo"},
            {"004.3", "Računarska mašinska oprema. Računarski hardver"},
            {"004.4", "Programska oprema. Softver"},
            {"004.42", "Računalniško programiranje. Računalniški programi"},
            {"004.43", "Računarski programski jezici"},
            {"004.45", "Sistemska programska oprema. Operacioni sistemi"},
            {"004.5", "Interakcija između čoveka i računara. Korisnički interfejs. Korisnička okolina"},
            {"004.55", "Hipermediji. Hipertekst"},
            {"004.6", "Podaci"},
            {"004.7", "Računarske komunikacije. Računarske mreže"},
            {"004.738.5", "Internet"},
            {"004.8", "Veštačka inteligencija. Veštački razum"},
            {"004.9", "Računalniške tehnike za namensko rabo"},
            {"004.92", "Računarska grafika"},
            {"004.94", "Simulacija. Oponašanje"},
            {"005", "Organizacija. Teorija organizacije"},
            {"006", "Standardizacija"},
            {"006.3/.8", "Standardi"},
            {"007", "Teorija informacija. Kibernetika"},
            {"007.5", "Automatski i upravljački sistemi"},
            {"007.52", "Robotika. Roboti"},
            {"008", "Kultura. Civilizacija (opšta pitanja). Progres"},
            {"008.2", "Futurologija"},
            {"009", "Humanističke nauke i umetnost uopšte"},
            {"01", "Bibliografija, teorija"},
            {"01(051)", "Bibliografije. Katalozi. Spiskovi knjiga"},
            {"011/014", "Bibliografije. Univerzalne i opšte bibliografije. Apstrakti i indeksi"},
            {"015", "Nacionalne bibliografije"},
            {"016", "Specijalne bibliografije. Referalni časopisi. Sekundarne publikacije"},
            {"016:929a/ž", "Biobibliografije"},
            {"017.3/.4", "Aukcijski katalozi. Prodajni katalozi knjiga"},
            {"017/019", "Bibliotečki katalozi"},
            {"02", "Bibliotekarstvo"},
            {"025.3", "Katalogizacija"},
            {"025.4", "Klasifikacija. Indeksiranje. Tezaurusi"},
            {"026", "Stručne biblioteke"},
            {"027", "Opšte biblioteke"},
            {"027.022", "Javne, opšte biblioteke"},
            {"027.54", "Narodne biblioteke"},
            {"027.7/.8", "Školske biblioteke. Visokoškolske biblioteke"},
            {"028", "Čitanje. Tehnika čitanja. Rad sa čitaocima"},
            {"030", "Opšta referensna dela. Opšte enciklopedije"},
            {"050", "Serijske publikacije. Periodika. Časopisi"},
            {"050.8/.9", "Adresari. Almanasi. Kalendari"},
            {"06", "Korporacije. Društva. Kongresi. Izložbe"},
            {"061", "Korporacije. Društva"},
            {"061.12", "Akademije"},
            {"061.2", "Nevladine korporacije i organizacije. Društva. Fondacije"},
            {"061.213", "Omladinske organizacije"},
            {"061.22", "Kulturna i umetnička društva"},
            {"061.3", "Sastanci. Simpozijumi. Kongresi"},
            {"061.4", "Izložbe. Sajmovi"},
            {"061.5(4/9)", "Poslovna preduzeća. Firme (adresari, jubilarni zbornici)"},
            {"061.6", "Naučne i tehničke ustanove (zavodi, instituti)"},
            {"069", "Muzeji. Muzeologija. Stalne izložbe. Muzejske zbirke"},
            {"070", "Žurnalizam. Novinarstvo"},
            {"070.48", "Uradni listi. Informativna glasila institucij in podjetij. Literarni listi. Reklamni in oglasni časopisi"},
            {"070.481", "Službeni listovi"},
            {"070.489", "Informativna glasila institucija i preduzeća"},
            {"082.1", "Knjižne zbirke. Izdavačke serije"},
            {"09", "Rokopisi. Retka i značajna dela"},
            {"091", "Rukopisi"},
            {"093", "Inkunabule"},
            {"094/096", "Retke knjige. Vredne knjige. Faksimili"},
            {"097", "Ekslibrisi. Monogrami, pečati"},
            {"1", "Filozofija (opšte)"},
            {"1 a/ž", "Filozofi"},
            {"1(091)", "Istorija filozofije"},
            {"1(3)", "Filozofija starog veka"},
            {"1(4)\"04/14\"", "Evropska filozofija, srednji vek"},
            {"1(4)\"15/19\"", "Evropska filozofija, novi vek"},
            {"1(4/9)\"19\"", "Savremena filozofija"},
            {"11/12", "Metafizika. Filozofija prirode (Kosmologija vidi i: 524)"},
            {"111.852", "Estetika"},
            {"130.2", "Filozofija kulture"},
            {"133", "Okultizam. Astrologija"},
            {"141", "Filozofski sistemi"},
            {"159.9", "Psihologija (opšte)"},
            {"159.92", "Psihičke sposobnosti i razvoj. Karakterologija. Stvaralaštvo"},
            {"159.93/.94", "Čulno zapažanje. Niži mentalni procesi"},
            {"159.95", "Viši mentalni procesi. Mišljenje"},
            {"159.96", "Posebna mentalna stanja i procesi"},
            {"159.964", "Dubinska psihologija. Psihoanaliza"},
            {"159.97", "Psihopatologija"},
            {"159.98", "Psihotehnike"},
            {"16", "Logika. Naučna sistematika"},
            {"165", "Teorija saznanja. Epistemologija"},
            {"165.75", "Strukturalizam"},
            {"17", "Etika"},
            {"2", "Religija. Teologija"},
            {"21", "Prirodne religije. Teodicije"},
            {"22", "Sveto pismo. Biblija"},
            {"22.0", "Izvodi i prerade tekstova Svetog pisma. Hermeneutika. Egsegeza"},
            {"22.043", "Biblijske priče. Sveto pismo za decu"},
            {"22.046", "Biblijske priče. Sveto pismo za decu"},
            {"221/224", "Stari zavet"},
            {"225/228", "Novi zavet"},
            {"23", "Dogmatska teologija. Opšta apologetika. Eshatologija"},
            {"23/28", "Hrišćanstvo"},
            {"231", "Bog"},
            {"238", "Simboli vere. Katihizis. Veroispovedanje"},
            {"24", "Moralna teologija"},
            {"242/245", "Meditacije. Molitve. Religijska književnost"},
            {"248", "Asketska i mistička teologija. Pobožnosti"},
            {"25", "Pastoralna teologija. Propovedi. Sveštenik kao pastor"},
            {"26", "Hrišćanska crkva uopšte. Crkva i pripadnost"},
            {"262", "Organizacija Crkve. Crkvena uprava"},
            {"264", "Liturgija. Bogosluženje"},
            {"265", "Sakramenti"},
            {"266/268", "Evangelizacija. Misionarski rad"},
            {"27", "Opšta istorija hrišćanske crkve"},
            {"271", "Verski redovi. Monaštvo"},
            {"276", "Patrologija. Crkveni oci"},
            {"28", "Hrišćanske crkve i sekte"},
            {"282", "Rimokatolička Crkva"},
            {"29", "Nehrišćanske religije"},
            {"291", "Poredbene studije i istorija religija. Hijerologija. Nove religije"},
            {"292", "Klasična mitologija"},
            {"294", "Budizam. Hinduizam (Joga vidi i: 615.851)"},
            {"296", "Jevrejska religija"},
            {"297", "Islam"},
            {"3", "Društvene nauke (opšte)"},
            {"303", "Metodologija i metode društvenih nauka"},
            {"304", "Socijalna politika"},
            {"308", "Sociografija. Deskriptivne studije društva"},
            {"308(4)", "Evropske države, društvene prilike"},
            {"308(497.11)", "Srbija, društvene prilike"},
            {"308(497.16)", "Crna Gora, društvene prilike"},
            {"308(5/9)", "Neevropske države, društvene prilike"},
            {"311", "Statistika"},
            {"311/314", "Statistika. Demografija"},
            {"314", "Demografija. Statistika prebivalstva"},
            {"314.7", "Migracije"},
            {"314.743(=1.497.16)", "Crnogorski iseljenici"},
            {"314.743(=861)", "Srpski iseljenici"},
            {"316", "Sociologija"},
            {"316.2", "Sociološke teorije. Sociološki pravci"},
            {"316.3", "Društvo. Društvena struktura. Globalno društvo"},
            {"316334", "Podsistemi i institucije globalnog društva. Sociologija rada. Sociologija politike. Sociologija ekoloških podsistema i institucija"},
            {"316.34", "Društvena stratifikacija. Društveno raslojavanje"},
            {"316346", "Demografska stratifikacija prema polu i starosti"},
            {"316.35", "Društvene grupe"},
            {"316.4", "Društveni procesi"},
            {"316.6", "Društveno ponašanje. Socijalna psihologija"},
            {"316.653", "Javno mnjenje. Javno mišljenje"},
            {"316.7", "Sociologija kulture"},
            {"316.77", "Sociologija komunikacij"},
            {"32", "Političke nauke"},
            {"32.01", "Politika, teorija. Političke teorije"},
            {"321", "Politički sistemi. Država"},
            {"322", "Država i crkva"},
            {"323", "Unutrašnja politika. Politička situacija"},
            {"323(497.11)", "Unutrašnja politika, Srbija"},
            {"323(497.16)", "Unutrašnja politika, Crna Gora"},
            {"323.1", "Narodni pokreti. Nacionalizam. Rasna segregacija. Etničke manjine"},
            {"323.15", "Nacionalne, etničke manjine"},
            {"323.15(=1.497.16)", "Crnogorci, nacionalne manjine"},
            {"323.15(=861)", "Srbi, nacionalne manjine"},
            {"324", "Izbori. Plebisciti. Referendumi"},
            {"325", "Kolonizacija. Kolonijalna politika. Borba za nezavisnost"},
            {"327", "Međunarodni odnosi. Svetska politika. Spoljna politika"},
            {"327(497.11)", "Srbija, spoljna politika"},
            {"327(497.16)", "Crna Gora, spoljna politika"},
            {"327.3", "Internacionalizam. Međunarodni pokreti"},
            {"327.5", "Međunarodni konflikti. Popuštanje napetosti"},
            {"328", "Parlamenti. Vlade"},
            {"329", "Političke partije i pokreti"},
            {"329(497.11)", "Političke partije u Srbiji"},
            {"329(497.16)", "Političke partije u Crnoj Gori"},
            {"33", "Privreda. Ekonomske nauke"},
            {"330", "Ekonomija. Ekonomisti. Ekonomske teorije"},
            {"330.1", "Politička ekonomija. Ekonomski zakoni. Kapital"},
            {"330.3", "Ekonomska gibanja. Družbena reprodukcija. Makroinvesticije"},
            {"330.34", "Ekonomski razvoj. Razvoj proizvodnih odnosa. Ekonomski sistemi"},
            {"330.4", "Matematička ekonomija. Ekonometrija"},
            {"330.5", "Nacionalna svojina. Društveni proizvod. Nacionalni dohodak. Potrošnja. Životni standard"},
            {"331", "Rad. Zaposlenost. Sindikati"},
            {"331.1", "Teorija i organizacija rada. Ergonomija"},
            {"331.103", "Organizacija rada. (Proučavanje rada vidi i: 65.015)"},
            {"331.105", "Radni odnosi. Poslodavci. Korisnici. Sindikati"},
            {"331.106", "Radni ugovori"},
            {"331.107", "Učešće korisnika u upravljanju. Industrijska demokratija. Samoupravljanje"},
            {"331.108", "Organizovanje kadrova. Radni poredak. Radna disciplina"},
            {"331.109", "Radni sporovi između poslodavaca i korisnika. Štrajk"},
            {"331.2", "Lični dohoci. Plate"},
            {"331.3", "Radno vreme. Odsustva. Godišnji odmori"},
            {"331.4", "Radna okolina. Radni uslovi"},
            {"331.45", "Zaštita na radu. Nesreće na radu"},
            {"331.5", "Zaposlenje. Tržište rada"},
            {"331.54", "Zanimanje"},
            {"331.548", "Profesionalna orijentacija. Savetovanje i konsultovanje oko izbora profesije"},
            {"331.56", "Nezaposlenost"},
            {"332", "Regionalna privreda. Teritorijalna privreda. Stambena privreda"},
            {"332.1", "Regionalna privreda"},
            {"332.2", "Zemlja sa stanovišta privrede"},
            {"332.26", "Povreda prava svojine (nacionalizacija, denacionalicija)"},
            {"332.8", "Stambena privreda"},
            {"334", "Oblici organizovanja i saradnje u privredi. Kooperacija (opšte)"},
            {"334.71", "Mala privreda"},
            {"334.72", "Preduzeća prema pravu svojine. Privatna preduzeća. Javna preduzeća. Multinacionalna preduzeća"},
            {"334.73", "Zadruge"},
            {"334.75/.76", "Privredna udruženja. Karteli. Koncerni. Trustovi"},
            {"334.788", "Privredne komore. Trgovinske komore"},
            {"336", "Finansije (opšte)"},
            {"336(051)", "Finansije. Javne finansije. Porezi. Carine"},
            {"336.1", "Javne finansije. Javni budžeti. Proračun. Javni dug"},
            {"336.1/.5", "Javne finansije. Javni prihodi. Proračun. Javni dug. Javna potrošnja"},
            {"336.22", "Porezi"},
            {"336.24", "Carine"},
            {"336.7", "Novac. Monetarni sistem. Bankarstvo. Berze"},
            {"336.71", "Banke. Bankarstvo"},
            {"336.74", "Novac. Valuta"},
            {"336.748", "Kurs novca. Kretanje kurseva. Inflacija. Stabilizacija"},
            {"336.76", "Berza. Tržište novca. Tržište kapitala. Vrednostni papirji"},
            {"336.77/.78", "Kreditni sistem"},
            {"338", "Privreda (kompleksni privredni prikazi pojedinih država, regija itd.)"},
            {"338(051)", "Privreda (kompleksni privredni prikazi pojedinih država, regija itd.). Ekonomska politika. Upravljanje privredom. Cene"},
            {"338(497.11)", "Srbija, privreda"},
            {"338(497.16)", "Crna Gora, privreda"},
            {"338.1", "Privredna situacija. Konjunktura. Recesija"},
            {"338.2", "Ekonomska politika. Ekonomsko planiranje"},
            {"338.24", "Ekonomska kontrola. Državna intervencija. Nacionalizacija. Denacionalizacija"},
            {"338.4", "Privredni sektori"},
            {"338.5", "Cene. Troškovi"},
            {"339", "Trgovina. Tržište. Marketing"},
            {"339.1", "Trgovina (opšta pitanja)"},
            {"339.13", "Tržišče uopšte. Analiza tržišta. Marketing. Konkurencija"},
            {"339.3", "Unutrašnja trgovina. Trgovinska mreža. Zaštita potrošača"},
            {"339.5", "Međunarodna trgovina. Politika spoljne trgovine. Carine"},
            {"339.7", "Međunarodne finansije. Međunarodni platni promet. Međunarodno tržište kapitala. Mednarodne banke"},
            {"339.74", "Devizna politika"},
            {"339.9", "Svetska privreda. Međunarodni ekonomski odnosi. Međunarodne ekonomske integracije. Globalna ekonomija"},
            {"339.923", "Međunarodne ekonomske integracije. Ekonomske unije. Ekonomske zajednice"},
            {"34", "Pravne nauke. Pravo (opšte). Zakonodavstvo"},
            {"34(091)", "Pravna istorija"},
            {"34(4/9)", "Pravni sistemi prema pojedinim državama"},
            {"340.1", "Pravo, teorija. Filozofija prava. Pozitivno pravo"},
            {"340.15", "Pravni sistemi"},
            {"340.6", "Pomoćne pravne nauke. Sudska medicina. Sudska psihijatrija"},
            {"341", "Međunarodno pravo"},
            {"341.1", "Međunarodne organizacije"},
            {"341.1+341.217", "Međunarodne organizacije"},
            {"341.2", "Subjekti i objekti u međunarodnom pravu. Državna suverenost. Međunarodne unije"},
            {"341.24", "Međunarodni pravni akti. Međunarodni dogovori. Međunarodni sporazumi"},
            {"341.3", "Ratno pravo. Humanitarno pravo"},
            {"341.7/.8", "Diplomatsko pravo. Konzularno pravo"},
            {"342", "Javno pravo. Državno pravo. Ustavno pravo. Upravno pravo"},
            {"342.4", "Ustavi. Zakonodavne skupštine"},
            {"342.5", "Državna vlast. Vlade. Parlamenti"},
            {"342.7", "Človekove pravice"},
            {"342.8", "Izborno pravo. Izborni sistemi"},
            {"343", "Krivično pravo"},
            {"343.1", "Krivično pravo. Krivični postupak"},
            {"343.3/.7", "Krivična dela. Vrste krivičnih dela"},
            {"343.8", "Penologija. Izvršavanje kazni. Kaznene sankcije. Kazneni zavodi"},
            {"343.9", "Kriminologija. Kriminalistika"},
            {"344", "Posebno krivično pravo. Vojno krivično pravo. Vazduhoplovno i pomorsko krivično pravo"},
            {"347", "Građansko pravo"},
            {"347.2", "Stvarno pravo"},
            {"347.23", "Svojina. Stvarno pravo"},
            {"347.4/.5", "Obligacijsko pravo"},
            {"347.61/.64", "Porodično pravo"},
            {"347.65/.68", "Nasledno pravo. Testament"},
            {"347.7", "Trgovinsko pravo. Privredno pravo"},
            {"347.72", "Trgovinska društva. Privredna društva"},
            {"347.77", "Industrijska svojina. Patentno pravo"},
            {"347.78", "Autorsko pravo. Zaštita autorskog prava"},
            {"347.9", "Pravni postupak. Ustrojstvo sudova i kadrova"},
            {"348", "Crkveno pravo. Kanonsko pravo"},
            {"349", "Posebne grane prava (socijalno pravo, pravo zaštite okoline. Atomsko i nuklearno pravo)"},
            {"349.2", "Radno pravo"},
            {"349.4", "Zemljišno pravo. Agrarno pravo. Propisi o gradnji. Pravo stanovanja"},
            {"35", "Javna uprava. Državna uprava (regionalna i lokalna uprava)"},
            {"35(497.11)", "Javna uprava u Srbiji"},
            {"35(497.16)", "Javna uprava u Crnoj Gori"},
            {"351", "Zadaci javne uprave. Javna svojina. Javni radovi"},
            {"351.74/.76", "Policija. Javni red i mir. Evidencija prebivališta. Nadzor nad javnim moralom"},
            {"351.778.5", "Stambena pitanja. Stanovi. Naselja"},
            {"352", "Lokalna upravo. Opštinska uprava. Najniži stepen uprave"},
            {"352/354", "Upravni stepeni. Regionalna uprava. Lokalna samouprava"},
            {"355.01", "Filozofija rata. Sociologija rata. Militarizam"},
            {"355.02", "Vojna politika. Politika državne odbrane"},
            {"355.3", "Organizacija oružanih snaga"},
            {"355.4", "Vojne operacije. Taktika i strategija"},
            {"355.48/.49", "Vojna istorija. Ratovi"},
            {"355/359", "Vojna veština. Vojne nauke"},
            {"36", "Socijalni rad. Socijalna pomoć"},
            {"364", "Socijalni problemi. Vrste socijalne pomoći"},
            {"368", "Osiguranje"},
            {"369", "Socijalno osiguranje"},
            {"37", "Vaspitanje. Obrazovanje. Nastava"},
            {"37(4/9)", "Obrazovni sistemi u pojedinim državama"},
            {"37(497.11)", "Obrazovni sistem u Srbiji"},
            {"37(497.16)", "Obrazovni sistem u Crnoj Gori"},
            {"37.01", "Osnovi obrazovanja, teorija. Pedagogija"},
            {"37.014", "Politika obrazovanja"},
            {"37.015", "Discipline pedagoške nauke (pedagoška psihologija)"},
            {"37.018", "Vaspitanje (osnovni oblici)"},
            {"37.02", "Didaktika (opšte)"},
            {"37.03", "Formiranje i razvoj ličnosti (moralno, socijalno, umetničko, ekološkovaspitanje)"},
            {"371", "Organizacija vaspitavanja i obrazovanja. Osoblje"},
            {"371.2", "Organizacija obrazovnih institucija i nastave"},
            {"371.3", "Nastavne metode i postupci. Oblici nastave"},
            {"371.3:0/9", "Nastavne metode za pojedine predmete"},
            {"371.4", "Vaspitni sistemi"},
            {"371.5", "Školski poredak i disciplina. Kazne"},
            {"371.6", "Položaj škola. Školska oprema"},
            {"371.64/.69", "Nastavna sredstva. Sredstva za podučavanje"},
            {"371.8", "Život i rad učenika i studenata"},
            {"372.3", "Predškolsko obrazovanje"},
            {"372.4", "Osnovno obrazovanje. Početna nastava"},
            {"372.8", "Posebni predmeti"},
            {"373", "Predškolske ustanove. Osnovne škole. Srednje škole"},
            {"374", "Obrazovanje i vaspitanje van škole. Obrazovanje odraslih"},
            {"376", "Specijalna pedagogija. Defektologija. Vaspitanje, obrazovanje i obučavanje posebnih grupa i osoba"},
            {"377", "Stručno obrazovanje. Profesionalne škole"},
            {"377.5", "Više škole"},
            {"378", "Visoko obrazovanje"},
            {"378(4/9)", "Visoko školstvo u pojedinim državama"},
            {"378(497.11)", "Visoko obrazovanje u Srbiji"},
            {"378(497.16)", "Visoko obrazovanje u Crnoj Gori"},
            {"378.18", "Studenti. Udruženja. Običaji. Proslave"},
            {"378.4", "Univerziteti"},
            {"378.60/.69", "Visoke škole po strukama"},
            {"379.8", "Slobodno vreme i rekreacija. Amaterizam. Hobi. Uradi sam"},
            {"389", "Metrologija"},
            {"39", "Etnologija. Običaji. Narodni praznici. Koledarski praznici. Ponašanje. Tradicije. Bonton"},
            {"39(=1.497.16)", "Crnogorska narodna kultura. Crnogorski narodni običaji"},
            {"39(=861)", "Srpska narodna kultura. Srpski narodni običaji"},
            {"391", "Nošnje. Moda. Nakit"},
            {"395", "Bonton. Pokloni"},
            {"396", "Feminizam. Žena i društvo. Položaj žene"},
            {"397", "Primitivni narodi. Indijanci. Cigani"},
            {"398", "Folklor u užem smislu. Narodni običaji"},
            {"398(497.4)", "Narodni običaji Slovenije"},
            {"5", "Prirodne nauke"},
            {"502", "Priroda. Zaštita i izučavanje prirode"},
            {"502/504", "Priroda. Izučavanje i čuvanje prirode. Ekologija"},
            {"504", "Ekologija"},
            {"504.03", "Socijalna ekologija"},
            {"504.05/.06", "Zagađenje životne sredine. Zaštita životne sredine"},
            {"504.3", "Životna sredina u atmosferi"},
            {"504.4", "Životna sredina u hidrosferi"},
            {"51", "Matematika"},
            {"51-7", "Matematika u drugim naukama"},
            {"51-8", "Matematičke igre i rekreacija"},
            {"510", "Teorija skupova. Matematička logika"},
            {"511", "Teorija brojeva. Aritmetika"},
            {"512", "Algebra"},
            {"512.5", "Viša algebra"},
            {"512.6", "Posebne grane algebre. Linearna algebra"},
            {"514", "Geometrija"},
            {"514.11", "Trigonometrija"},
            {"514.18", "Opisna geometrija"},
            {"514.7", "Diferencijalna geometrija. Vektorska algebra. Tenzorska algebra"},
            {"515.1", "Topologija"},
            {"515.14", "Algebarska topologija"},
            {"517", "Matematička analiza"},
            {"517.1/.4", "Diferencijalni račun. Integralni račun. Operatorski račun. Fourierova transformacija. Laplaceova transformacija"},
            {"517.5", "Opšta teorija funkcija"},
            {"517.9", "Diferencijalne jednačine. Integralne jednačine. Varijacijski račun. Funkcionalna analiza"},
            {"519.1", "Kombinatorna analiza"},
            {"519.17", "Teorija grafova"},
            {"519.2", "Matematička statistika. Teorija verovatnoće"},
            {"519.6", "Numerička analiza. Matematičko programiranje"},
            {"519.68", "Programiranje računara (teorija, jezici, računarska logika) (Programska oprema vidi: 681.3.06)"},
            {"519.688", "Aplikativni računarski programi"},
            {"519.7", "Matematička kibernetika. Matematička lingvistika"},
            {"519.7/.8", "Matematička kibernetika. Operaciono istraživanje"},
            {"519.8", "Operaciono istraživanje (glej tudi: 65.012.122)"},
            {"52", "Astronomija. Astrofizika. Istraživanje svemira"},
            {"520", "Astronomski instrumenti"},
            {"521", "Teorijska astronomija. Nebeska mehanika"},
            {"523", "Sunčev sistem"},
            {"524", "Zvezdani sistemi. Vasiona. Kosmologija (Filozofija prirode vidi: 11/12)"},
            {"527", "Navigacija. Nautička i aeronautička astronomija"},
            {"528", "Geodezija. Fotogrametrija. Kartografija"},
            {"528.7", "Fotogrametrija"},
            {"528.9", "Kartografija (tekstualna dokumentacija)"},
            {"529", "Hronologija. Određivanje vremena"},
            {"53", "Fizika"},
            {"530.12", "Teorija relativnosti"},
            {"530.14", "Kvantna teorija. Principi konstantnosti i promenljivosti"},
            {"530.16", "Uzročnost i verovatnoća. Haos"},
            {"531/533", "Mehanika"},
            {"531/534", "Mehanika. Akustika"},
            {"534", "Akustika. Vibracije"},
            {"535", "Optika"},
            {"536", "Toplota. Termodinamika"},
            {"536.7", "Termodinamika. Toplotna energija"},
            {"537", "Elektricitet. Magnetizam. Elektromagnetizam"},
            {"538.9", "Fizika kondenzovane materije"},
            {"539", "Fizička priroda materija"},
            {"539.1", "Nuklearna, atomska i molekularna fizika"},
            {"539.16", "Radioaktivnost"},
            {"539.17", "Fisija"},
            {"539.18", "Atomska fizika"},
            {"539.19", "Molekularna fizika"},
            {"539.2", "Osobine i struktura molekulskih sistema"},
            {"539.3", "Mehanika elastičnih tela. Elastičnost. Deformacije"},
            {"539.4", "Tvrdoća. Čvrstoća"},
            {"54", "Hemija"},
            {"542", "Eksperimentalna hemija. Laboratorijska hemija"},
            {"543", "Analitička hemija"},
            {"543.061", "Kvalitativna analiza"},
            {"543.062", "Kvantitativna analiza"},
            {"543.2/.9", "Hemijske metode analize. Analitička metoda"},
            {"544", "Fundamentalna hemija. Fizikalna hemija"},
            {"544.1", "Hemijska struktura"},
            {"544.3/.4", "Hemijska termodinamika. Hemijska ravnoteža. Hemijska kinetika"},
            {"544.5/.6", "Hemija procesa visokih energija. Elektrohemija"},
            {"544.7", "Površinska hemija. Koloidna hemija"},
            {"546", "Neorganska hemija"},
            {"546.1/.2", "Nemetali"},
            {"546.3/.9", "Metali"},
            {"547", "Organska hemija"},
            {"547.2", "Aciklična jedinjenja"},
            {"547.5", "Ciklična jedinjenja"},
            {"547.7", "Heterociklična jedinjenja"},
            {"547.9", "Prirodne supstance. Supstance nepoznatog sastava"},
            {"548/549", "Kristalografija. Mineralogija"},
            {"55", "Geologija"},
            {"550.3", "Geofizika"},
            {"551.1/.4", "Opšta geologija. Speleologija. Geomorfologija"},
            {"551.5", "Meteorologija. Klimatologija"},
            {"551.7", "Istorijska geologija. Stratigrafija"},
            {"552", "Petrografija"},
            {"553", "Nauka o rudama. Ekonomska geologija. Mineralna ležišta"},
            {"556", "Hidrologija"},
            {"556.3", "Podzemne vode. Hidrogeologija"},
            {"556.5", "Površinske vode"},
            {"56", "Paleontologija. Sistematska paleobotanika. Sistematska paleozoologija"},
            {"57", "Biologija"},
            {"572", "Antropologija"},
            {"574", "Ekosistemi. Hidrobiologija. Biogeografija"},
            {"575", "Opšta genetika. Imunogenetika. Postanak vrsta. Filogenija"},
            {"575.8", "Evolucija. Nastanak vrsta. Filogenija"},
            {"576", "Citologija"},
            {"577", "Biohemija. Molekularna biologija. Biofizika"},
            {"577.2", "Molekularne osnove života. Molekularna biologija. Molekularna genetika"},
            {"578", "Virusologija"},
            {"579", "Mikrobiologija"},
            {"579.6", "Primenjena mikrobiologija"},
            {"58", "Botanika"},
            {"581", "Opšta botanika. Fiziologija biljaka. Anatomija biljaka. Ekologija biljaka"},
            {"581.9", "Geografija biljaka. Fitogeografija"},
            {"582", "Sistematska botanika. Sistematika biljaka"},
            {"59", "Zoologija"},
            {"591", "Opšta zoologija. Fiziologija životinja. Anatomija životinja. Ekologija životinja"},
            {"591.9", "Zoogeografija"},
            {"592/599", "Sistematska zoologija"},
            {"61", "Medicina"},
            {"611", "Anatomija"},
            {"612", "Fiziologija"},
            {"613", "Higijena"},
            {"613.2", "Dijetetika"},
            {"613.8", "Higijena nervnog sistema. Higijena i moral. Ovisnost"},
            {"614", "Javno zdravstvo i higijena. Sanitarna inspekcija. Prevencija"},
            {"614.2", "Javna i profesionalna organizacija zdravstvene službe"},
            {"614.8", "Udesi. Opasnosti od udesa. Prevencije udesa"},
            {"614.84", "Požari. Protivpožarna zaštita. Vatrogastvo"},
            {"614.88", "Prva pomoć. Crveni krst"},
            {"615", "Farmacija. Farmakologija"},
            {"615.2", "Lekovi prema svom najvažnijem dejstvu"},
            {"615.3", "Lekovi prema poreklu"},
            {"615.4", "Farmaceutski preparati. Medicinski materijali i oprema"},
            {"615.8", "Fizioterapija. Radioterapija. Ostali medicinski terapeutski tretmani. Alternativna medicina"},
            {"615.82/.84", "Medicinska rehabilitacija. Fizioterapija. Radioterapija"},
            {"615.851", "Psihoterapija. Joga"},
            {"615.89", "Narodna medicina. Domaći lekovi"},
            {"615.9", "Toksikologija"},
            {"616", "Patologija. Klinička medicina"},
            {"616-001", "Povrede. Traume. Rane"},
            {"616-002.5", "Tuberkuloza"},
            {"616-002.77", "Reumatizam"},
            {"616-006", "Onkologija. Neoplazme. Tumori"},
            {"616-053.2", "Pedijatrija. Dečje bolesti"},
            {"616-053.9", "Gerijatrija. Gerontologija"},
            {"616-057", "Medicina rada. Profesionalna oboljenja"},
            {"616-058", "Socijalna medicina"},
            {"616-07", "Semiologija. Simptomatologija. Dijagnostika"},
            {"616-083", "Nega bolesnika"},
            {"616-084", "Preventivna medicina. Profilaksa"},
            {"616-089", "Hirurgija. Operativne tehnike"},
            {"616-092", "Patološka fiziologija"},
            {"616-097", "Antigeni. Antitela. Imunologija"},
            {"616.1", "Bolesti srca i krvotoka. Hematologija"},
            {"616.1/.4", "Interna medicina"},
            {"616.2", "Bolesti organa za disanje"},
            {"616.21/.23", "Otorinolaringologija"},
            {"616.3", "Gastroenterologija"},
            {"616.31", "Stomatologija"},
            {"616.379", "Diabetes"},
            {"616.4", "Endokrinologija. Bolesti limfnog sistema"},
            {"616.5", "Dermatologija. Kožne bolesti"},
            {"616.6", "Urologija. Bolesti urogenitalnog sistema"},
            {"616.7", "Bolesti organa za kretanje"},
            {"616.8", "Neurologija. Neuropatologija. Nervni sistem"},
            {"616.89", "Psihijatrija. Psihopatologija. Emocionalni poremećaji"},
            {"616.9", "Infektivne (zarazne) bolesti. AIDS. Venerologija"},
            {"617", "Hirurgija"},
            {"617.3", "Ortopedija"},
            {"617.7", "Oftalmologija. Očne bolesti"},
            {"618", "Ginekologija. Porodiljstvo. Akušerstvo"},
            {"619", "Veterina"},
            {"619:616", "Bolesti domaćih životinja"},
            {"619:636", "Veterinarski tretman određenih vrsta domaćih životinja"},
            {"62", "Inženjerstvo. Tehnika uopšte"},
            {"62-5", "Režim rada i upravljanje mašinama i procesima"},
            {"620.1/.2", "Ispitivanje materijala. Greške u materijalu. Zaštita materijala. Trgovinski materijali"},
            {"620.9", "Energetska privreda (uopšte)"},
            {"620.92", "Alternativni izvori energije"},
            {"621", "Opšte mašinstvo"},
            {"621.039", "Nuklearna tehnika. Atomska energija i industrija"},
            {"621.039.58", "Odvajanje fisionog materijala. Čuvanje radioaktivnog materijala. Problemi sigurnosti"},
            {"621.039.7", "Tretiranje radioaktivnih otpadaka"},
            {"621.1", "Proizvodnja i korišćenje vodene pare. Parne mašine"},
            {"621.22", "Hidraulična energija. Hidromotori. Vodne turbine"},
            {"621.3", "Elektrotehnika"},
            {"621.31", "Elektroenergetika"},
            {"621.311", "Elektrane. Električna mreža. Elektrifikacija"},
            {"621.313/.314", "Električne mašine. Pretvaranje električne energije. Transformatori. Ispravljači"},
            {"621.317", "Električna merenja"},
            {"621.35/.36", "Elektrohemijska tehnika. Termoelektrotehnika"},
            {"621.38", "Elektronika. Fotoćelije. Rentgenska tehnika"},
            {"621.39", "Telekomunikaciona tehnika"},
            {"621.396/.398", "Radiotehnika. TV tehnika. Video tehnika"},
            {"621.4", "Toplotne mašine (izuzev parnih mašina)"},
            {"621.5/.6", "Pneumatske mašine. Rashladne mašine. Kompresori. Postupci sa plinom. Skladišćenje i distribucija"},
            {"621.7", "Principi obrade materijala. Obrada bez rezanja. Toplotna obrada"},
            {"621.7+621.9", "Obrada i rukovanje materijalom. Alati, mašine, oprema itd."},
            {"621.74", "Livarstvo. Kalupljenje i livenje"},
            {"621.791", "Zavarivanje"},
            {"621.798", "Pakovanje. Pakovanje i oprema za pakovanje"},
            {"621.8", "Mašinski elementi. Transportni uređaji. Podmazivanje"},
            {"621.9", "Obrada sa rezanjem. Obrada skidanjem opiljaka. Brušenje. Testere. Čekići, prese"},
            {"622", "Rudarstvo. Rudarska tehnika. Rudarski radovi i istraživanja"},
            {"622.3", "Rudarstvo (pojedini minerali npr.: dobijanje nafte, ugljeni)"},
            {"622.7", "Bogaćenje mineralnih sirovina"},
            {"622.8", "Opasnost u rudnicima. Nesreće u jami"},
            {"623", "Vojna tehnika"},
            {"624", "Građevinarstvo i konstrukcije uopšte (Građevinski zanati vidi: 69, Građevinski materijali vidi: 691, Građevinski delovi vidi: 692)"},
            {"624+69", "Građevinska tehnika. Građevinarstvo i konstrukcije uopšte"},
            {"624.04", "Grafička i analitička statika za ispitivanje i proračun konstrukcija"},
            {"624.07", "Konstruktivni elementi"},
            {"625", "Niskogradnja u kopnenom transportu. Izgradnja železničkih, pruga. Izgradnja puteva"},
            {"625.1", "Železničke pruge, gradnja"},
            {"625.7/.8", "Putevi, gradnja"},
            {"626/627", "Hidrotehnika"},
            {"628", "Sanitarna tehnika"},
            {"628.1", "Snabdevanje vodom"},
            {"628.3", "Otpadne vode"},
            {"628.4", "Komunalna higijena"},
            {"628.5", "Industrijska higijena. Tehnička zaštita"},
            {"629", "Tehnika transportnih vozila"},
            {"629.3", "Tehnika kopnenih vozila (izuzev šinskih vozila)"},
            {"629.4", "Tehnika šinskih vozila"},
            {"629.5", "Tehnika plovila. Brodogradnja"},
            {"629.7", "Tehnika vazdušnog i prostornog transporta. Aeronautika. Kosmička tehnika"},
            {"63", "Poljoprivreda i srodne nauke"},
            {"630", "Šumarstvo"},
            {"630*3", "Eksploatacija šuma. Seča i transport. Šumsko inženjerstvo"},
            {"631", "Poljoprivreda (uopšte). Poljoprivredna tehnologija"},
            {"631.4", "Pedologija. Istraživanje zemljišta"},
            {"631.5", "Poljoprivredni radovi"},
            {"632", "Zaštita biljaka. Biljne bolesti"},
            {"633", "Poljski usevi i njihova proizvodnja"},
            {"634.1/.7", "Voćarstvo"},
            {"634.8+663.2", "Vinogradarstvo. Vinarstvo. Enologija"},
            {"635", "Vrtlarstvo. Vrtne biljke. Hortikultura"},
            {"636", "Stočarstvo i gajenje životinja uopšte"},
            {"636.1/.9", "Domaće životinje"},
            {"636/637", "Stočarstvo i gajenje životinja uopšte. Proizvodi od domaćih životinja i divljači"},
            {"637", "Proizvodi od domaćih životinja i divljači"},
            {"638", "Pčelarstvo i pčelinji proizvodi"},
            {"639", "Lov. Ribolov. Gajenje riba. Akvaristika"},
            {"64", "Domaćinstvo. Stanovanje"},
            {"640", "Ugostiteljstvo. Hotelijerstvo"},
            {"641", "Prehrambeni proizvodi. Priprema"},
            {"65", "Rukovođenje i organizacija rada u industriji, trgovini i saobraćaju"},
            {"65.01", "Teorija i praksa organizacije"},
            {"65.011", "Poslovna politika. Produktivnost"},
            {"65.012", "Teorija rukovođenja. Menadžment. Planiranje"},
            {"65.015", "Organizacija rada. Studija rada. Radni postupak. Radne faze"},
            {"65.018", "Kvalitet. Kvalifikacija"},
            {"651", "Kancelarijska služba"},
            {"651.75", "Poslovna korespondencija"},
            {"651.9", "Pisanje. Kucanje. Stenografija"},
            {"654", "Telekomunikacije. Radio. TV (organizacija, poslovanje, programi)"},
            {"655", "Grafička industrija. Štamparstvo"},
            {"655.1", "Štamparstvo uopšte"},
            {"655.4/.5", "Izdavaštvo i knjižarstvo uopšte"},
            {"656", "Saobraćaj (organizacija i kontrola). Transportne usluge"},
            {"656.1", "Drumski saobraćaj"},
            {"656.2", "Železnički saobraćaj"},
            {"656.6", "Pomorski saobraćaj. Transport vodenim putem. Plovidba"},
            {"656.7", "Vazdušni saobraćaj"},
            {"656.8", "PTT. Poštanske marke. Filatelija"},
            {"657", "Knjigovodstvo. Računovodstvo"},
            {"657.3", "Budžeti. Zaključivanje računa. Poslovne knjige. Bilansi"},
            {"657.4", "Računi. Knjigovodstveni sistemi. Pogonsko knjigovodstvo"},
            {"657.6", "Kontrola poslovanja. Revizija"},
            {"658", "Poslovno rukovođenje. Administracija. Komercijalna organizacija"},
            {"658.1", "Oblici i vrste preduzeća. Privatna preduzeća. Javna preduzeća"},
            {"658.14/.17", "Finansiranje preduzeća. Poslovne finansije"},
            {"658.2", "Postrojenja i proizvodni pogoni (zgrade, zemljište i materijali)"},
            {"658.3", "Zaposleni. Kadrovska politika. Obrazovanje kadrova"},
            {"658.5", "Proizvodnja (organizacija i planiranje)"},
            {"658.562", "Kontrola kvaliteta"},
            {"658.6", "Proizvodi. Industrijski proizvodi"},
            {"658.6/.9", "Komercijalna istraživanja i praksa. Nabavka. Prodaja"},
            {"658.7", "Nabavka. Kupovina"},
            {"658.8", "Prodaja. Marketing. Distribucija"},
            {"659", "Reklama. Odnosi sa javnošću"},
            {"659.1", "Reklama"},
            {"659.2", "Informacije. Informisanje. Informacioni sistemi"},
            {"659.2:004", "Informatika"},
            {"659.2:681.3", "Informatika"},
            {"659.3/.4", "Sredstva javnog informisanja. Obaveštavanje najšire javnosti"},
            {"66", "Hemijska i srodne industrije"},
            {"66.02", "Hemijska tehnika (tehnološki postupci i oprema)"},
            {"661", "Hemikalije. Pojedine grane hemijske industrije"},
            {"662", "Eksplozivi. Goriva"},
            {"663", "Industrijska mikrobiologija. Fermentacije, pića"},
            {"664", "Prehrambena industrija"},
            {"665", "Ulja. Masti. Voskovi"},
            {"665.5", "Kozmetika"},
            {"665.6/.7", "Naftna industrija"},
            {"666", "Staklo. Emajl. Tehnička keramika. Cement. Beton"},
            {"667", "Industrija boja"},
            {"669", "Metalurgija"},
            {"669.1", "Crna metalurgija. Gvožđe. Čelik"},
            {"669.2/.8", "Metalurgija obojenih metala"},
            {"67/68", "Razne industrije, zanati i umetnički zanati"},
            {"674", "Drvna industrija"},
            {"675", "Industrija kože. Štavljenje kože. Imitacija kože"},
            {"676", "Industrija celuloze, papira i kartona"},
            {"677", "Tekstilna industrija"},
            {"678", "Industrija gume i plastičnih masa"},
            {"681", "Precizna mehanika"},
            {"681.3", "Računari. Mašinska oprema. Automatska obrada podataka"},
            {"681.3.06", "Računari. Programska oprema. (Računarsko programiranje (teorija,jezici,logika) vidi: 519.68)"},
            {"681.324", "Računarske mreže"},
            {"681.5", "Automatska kontrola. Kontrolni sistemi.Kibernetika i tehnologija automatizacije"},
            {"681.8", "Tehnička akustika. Muzički instrumenti"},
            {"684", "Industrija nameštaja i srodne industrije. Tapetarstvo"},
            {"687", "Industrija odeće. Konfekcija"},
            {"69", "Građevinski zanati"},
            {"691", "Građevinski materjiali i elementi"},
            {"692", "Građevinski delovi i konstruktivni elementi"},
            {"693", "Zidarski radovi"},
            {"694", "Drvene konstrukcije. Tesarski radovi. Stolarski radovi"},
            {"696", "Instalacije u zgradama. Priključci. Oprema"},
            {"697", "Grejanje. Ventilacija i klimatizacija zgrada"},
            {"699.8", "Zaštita zgrada. Protivpožarna zaštita. Mere u slučaju opasnosti. Preventiva"},
            {"7", "Umetnost"},
            {"7(1/9)", "Umetnost prema pojedinim zemljama"},
            {"7.01", "Teorija umetnosti. Estetika. Filozofija"},
            {"7.02", "Umetnička tehnika. Zanatstvo"},
            {"7.025", "Restauracija. Konzervacija"},
            {"7.03", "Istorija umetnosti. Stilovi, škole, periodi i faze"},
            {"7.031", "Primitivna umetnost. Narodna umetnost"},
            {"7.04", "Objekti umetničkog predstavljanja. Ikonologija. Ikonografija"},
            {"7.046", "Religijska umetnost"},
            {"7.05", "Primenjena umetnost. Industrijsko oblikovanje. Komercijalni dizajn"},
            {"7.07", "Zanimanja i aktivnosti povezane sa umetnošću i zabavom"},
            {"71", "Prostorno planiranje i uređenje. Pejzaži, parkovi, vrtovi"},
            {"71/72", "Prostorno planiranje. Urbanizam. Arhitektura"},
            {"711.4", "Planiranje naselja. Urbanizam"},
            {"719", "Zaštita spomenika"},
            {"719:502", "Spomenici prirode. Prirodna baština"},
            {"719:7", "Umetnički spomenici"},
            {"72", "Arhitektura"},
            {"72(1/9)", "Arhitektura prema pojedinim zemljama"},
            {"72.01", "Arhitektura, estetika. Teorija arhitekture. Projektovanje"},
            {"72.03", "Arhitektura, istorija"},
            {"72.04", "Arhitekturni detalji i dekoracije"},
            {"72.071", "Arhitekti"},
            {"725", "Javne, upravne, poslovne, industrijske zgrade"},
            {"726", "Religijska, crkvena arhitektura"},
            {"727", "Zgrade za obrazovne, naučne i kulturne namene. Škole. Biblioteke"},
            {"728", "Stambena arhitektura. Stambena zgrada"},
            {"728.8", "Tvrđave. Zamkovi. Dvorci"},
            {"728.81", "Tvrđave. Zamkovi. Dvorci"},
            {"73", "Plastične umetnosti. Umetničko oblikovanje keramike. Umetničko oblikovanje metala. Zlatarstvo. Srebrarstvo"},
            {"73/76", "Likovne umetnosti"},
            {"73/76(064)", "Izložbeni katalozi likovne umetnosti. Zajedničke izložbe"},
            {"730", "Vajarstvo. Skulptura"},
            {"730(1/9)", "Vajarstvo prema pojedinim zemljama"},
            {"730.03", "Vajarstvo, istorija"},
            {"730.071", "Vajari"},
            {"737", "Numizmatika"},
            {"74", "Crtanje. Dizajn"},
            {"741.5", "Karikatura"},
            {"744", "Tehničko, linearno i geometrijsko crtanje"},
            {"745/749", "Primenjena umetnost. Umetničko oblikovanje drveta, tekstila, kože, papira, stakla itd. Umetnički zanati. Ručni radovi"},
            {"746", "Ručni radovi. Pletenje. Kukičanje. Veženje"},
            {"747", "Unutrašnja dekoracija"},
            {"75", "Slikarstvo"},
            {"75(1/9)", "Slikarstvo prema pojedinim državama"},
            {"75.03", "Slikarstvo, istorija"},
            {"75.071", "Slikari"},
            {"76", "Grafika"},
            {"766", "Grafičko oblikovanje. Plakati"},
            {"769.81", "Slikovnice. Ilustracije"},
            {"769.9", "Stripovi (uključujući studije)"},
            {"77", "Fotografija. Fotografski postupci. Fotografski snimci. Dokumentarna fotografija"},
            {"77.02", "Fotografska tehnika"},
            {"77.04", "Umetnička fotografija. Fotografski motivi"},
            {"77.04(064)", "Umetnička fotografija. Izložbeni katalozi"},
            {"778", "Posebne fotografske tehnike. Reprografija. Mikrografija. Projekcija"},
            {"778.5", "Kinematografska tehnika. Filmska fotografija"},
            {"78", "Muzika (opšte). Muzikologija. Muzičko vaspitanje"},
            {"78(1/9)", "Muzika prema pojedinim državama"},
            {"78.01", "Muzička estetika. Muzička filozofija"},
            {"78.03", "Muzika, istorija. Stilski periodi"},
            {"78.07", "Muzički stvaraoci, kompozitori, dirigenti, muzikolozi"},
            {"78.08", "Muzički oblici"},
            {"781", "Teorija muzike. Etnomuzikologija"},
            {"782", "Opere. Operete. Pozorišna muzika"},
            {"782/785", "Vrste muzike"},
            {"783", "Crkvena muzika. Liturgijska muzika"},
            {"784", "Vokalna muzika. Narodne pesme. Pevački horovi"},
            {"784.66", "Zabavna glasba"},
            {"784.9", "Tehnika pevanja. Solfeđo. Vežbe pevanja"},
            {"785", "Instrumentalna muzika. Orkestarska muzika. Kamerna muzika. Džez"},
            {"786/789", "Muzika za pojedinačne instrumente (Muzički instrumenti vidi: 681.8)"},
            {"78:37", "Muzičko obrazovanje. Muzika (udžbenici)"},
            {"791", "Razonoda. Spektakli. Izložbe"},
            {"791.4", "Film (opšte). Filmske vrste. Kinematografija"},
            {"791.4(1/9)", "Film prema pojedinim državama"},
            {"791.44", "Filmska produkcija. Filmski stvaraoci"},
            {"792", "Pozorište (opšte)"},
            {"792(1/9)", "Pozorište prema pojedinim državama"},
            {"792(497.11)", "Srbijansko pozorište"},
            {"792(497.16)", "Crnogorsko pozorište"},
            {"792.02/.09", "Pozorišni umetnici. Pozorišna tehnika"},
            {"792.2/.9", "Pozorišne vrste"},
            {"793/794", "Društvene zabave. Ples. Igre s kartama. Igre na tabli i stolu"},
            {"794.1", "Šah"},
            {"796.01", "Sport, teorija"},
            {"796.1", "Terenske igre i rekreacija. Dečje igre"},
            {"796.3", "Igre s loptom"},
            {"796.4", "Gimnastika. Atletika"},
            {"796.5", "Alpinizam. Planinarenje. Logorovanje"},
            {"796.6/.7", "Biciklizam. Automobilizam. Motoristika"},
            {"796.8", "Borilačke veštine. Borilački sportovi"},
            {"796.9", "Zimski sportovi. Sportovi na ledu"},
            {"796/799", "Sport. Fizičko vežbanje"},
            {"797", "Sportovi v vazduhu. Sportovi na vodi"},
            {"798/799", "Konjički sport. Lov. Ribolov. Streljaštvo"},
            {"80", "Filologija (opšte"},
            {"801.6", "Prozodija (metar, vrste stiha, rima)"},
            {"801.73", "Hermeneutika. Tekstologija. Interpretacije"},
            {"808", "Književna aktivnost i književna tehnika. Pisanje. Izdavanje. Kazivanje"},
            {"81", "Opšta pitanja lingvistike"},
            {"81'1", "Opšta lingvistika"},
            {"81'22", "Semiotika. Neverbalna komunikacija"},
            {"81'24", "Praktično znanje jezika. Bilingvizam (Udžbenici vidi pod pojedinačnim jezicima)"},
            {"81'25", "Teorija prevođenja. Prevođenje"},
            {"81'27", "Sociolingvistika"},
            {"81'34", "Fonetika. Fonologija. Glasovi"},
            {"81'36", "Gramatika"},
            {"81'373", "Leksikologija. Etimologija. Tvorba reči"},
            {"81'374", "Leksikografija. Rečnici"},
            {"81'38", "Stilistika"},
            {"81'42", "Tekstualna lingvistika. Analiza diskursa"},
            {"81-11", "Škole i smerovi u lingvistici. Strukturalizam"},
            {"811", "Lingvistika pojedinig jezika i jezičkih grupa"},
            {"811.1", "Indoevropski jezici, izuzev orijentalnih"},
            {"811.11", "Germanski jezici"},
            {"811.111", "Engleski jezik"},
            {"811.111(075)", "Engleski jezik (udžbenici)"},
            {"811.112", "Nemački jezik"},
            {"811.112.2", "Nemački jezik"},
            {"811.112.2(075)", "Nemački jezik (udžbenici)"},
            {"811.12+811.14", "Klasični jezici"},
            {"811.124", "Latinski jezik"},
            {"811.13", "Romanski jezici"},
            {"811.131.1", "Italijanski jezik"},
            {"811.131.1(075)", "Italijanski jezik (udžbenici)"},
            {"811.133.1", "Francuski jezik"},
            {"811.133.1(075)", "Francuski jezik (udžbenici)"},
            {"811.134.2", "Španski jezik"},
            {"811.134.2(075)", "Španski jezik (udžbenici)"},
            {"811.14", "Grčki jezik (klasični i moderni)"},
            {"811.16/.17", "Slovenski jezici. Baltički jezici"},
            {"811.161", "Ruski jezik. Drugi istočnoslovenski jezici"},
            {"811.161.1(075)", "Ruski jezik (udžbenici)"},
            {"811.162", "Zapadnoslovenski jezici"},
            {"811.163", "Južnoslovenski jezici"},
            {"811.163.4", "Srpski jezik. Hrvatski jezik"},
            {"811.163.4(075)", "Srpski jezik (udžbenici). Hrvatski jezik (udžbenici)"},
            {"811.163.41/.42", "Srpsko-hrvatski jezik"},
            {"811.163.6", "Slovenački jezik"},
            {"811.163.6(075)", "Slovenački jezik (udžbenici)"},
            {"811.21/.41", "Drugi indoevropski jezici. Orijentalni jezici. Hamitski jezici"},
            {"811.42/.45", "Afrički jezici"},
            {"811.51/.71", "Azijski jezici. Finski jezik. Mađarski jezik"},
            {"811.8", "Indijanski jezici"},
            {"811.9", "Veštački jezici"},
            {"81:1", "Filozofija jezika"},
            {"82", "Književnost (opšte). Istorija književnosti"},
            {"82.0", "Teorija književnosti"},
            {"82.02", "Književne škole i pravci"},
            {"82.09", "Književna kritika. Komparativna nauka o književnosti"},
            {"821", "Svetska književnost. Antologije. Čitanke"},
            {"821.0", "Svetska književnost (studije)"},
            {"821.09", "Svetska književnost (studije)"},
            {"821.1", "Germanske književnosti"},
            {"821.1.09", "Germanske književnosti (študije)"},
            {"821.1/.8", "Književnost pojedinih naroda"},
            {"821.11", "Germanske književnosti"},
            {"821.11.09", "Germanske književnosti (studije)"},
            {"821.111", "Engleska književnost"},
            {"821.111()", "Ostale engleske književnosti, država Komonvelta, Kanade, Australije (uključujući studije)"},
            {"821.111(73)", "Američka književnost"},
            {"821.111(73).09", "Američka književnost (studije)"},
            {"821.111.09", "Engleska književnost (studije)"},
            {"821.112.2", "Nemačka književnost (uključujući austrijsku, švajcarsku, jidiš)"},
            {"821.112.2.09", "Nemačka književnost (studije)"},
            {"821.124+821.14", "Klasične književnosti (uključujući študije)"},
            {"821.124.09", "Latinska književnost (studije)"},
            {"821.13", "Romanske književnosti (uključujući studije)"},
            {"821.131.1", "Italijanska književnost"},
            {"821.131.1.09", "Italijanska književnost (studije)"},
            {"821.133.1", "Francuska književnost"},
            {"821.133.1.09", "Francuska književnost (studije)"},
            {"821.134(7/8)", "Latinoameričke književnosti"},
            {"821.134(7/8).09", "Latinoameričke književnosti (studije)"},
            {"821.134.2", "Španska književnost"},
            {"821.134.2.09", "Španska književnost (studije)"},
            {"821.14.09", "Grčka književnost (studije)"},
            {"821.16.09", "Slovenske književnosti (studije)"},
            {"821.16/.17", "Slovenske književnosti. Baltičke književnosti"},
            {"821.161.1", "Ruska književnost"},
            {"821.161.1.09", "Ruska književnost (studije)"},
            {"821.162.1", "Poljska književnost (uključujući studije)"},
            {"821.162.3", "Češka književnost (uključujući studije)"},
            {"821.162.3/.4", "Češka književnost. Slovačka književnost"},
            {"821.162.4", "Slovačka književnost (uključujući studije)"},
            {"821.163", "Južnoslovenske književnosti (uključujući studije)"},
            {"821.163.4", "Srpska i hrvatska književnost"},
            {"821.163.4(497.6)", "Srpska i hrvatska književnost u BiH (uključujući studije)"},
            {"821.163.4-93", "Srpska i hrvatska dječja književnost (uključujući studije)"},
            {"821.163.4.09", "Srpska i hrvatska književnost (studije)"},
            {"821.163.41", "Srpska književnost"},
            {"821.163.41:398", "Srpska književnost (Narodna knjizevnost)"},
            {"821.163.41.09", "Srpska književnost (Knjizevne kritike i studije)"},
            {"821.163.41.09 A/Z", "Srpska književnost (Dela odredjenog autora)"},
            {"821.163.41-1", "Srpska književnost (Poezija)"},
            {"821.163.41-31", "Srpska književnost (Romani)"},
            {"821.163.41-32", "Srpska književnost (Pripovetke)"},
            {"821.163.41-342", "Srpska književnost (Basne)"},
            {"821.163.41-343", "Srpska književnost (Legende)"},
            {"821.163.41-344", "Srpska književnost (Bajke)"},
            {"821.163.41-36", "Srpska književnost (Kratke price. Anegdote. Sale)"},
            {"821.163.41-4", "Srpska književnost (Eseji)"},
            {"821.163.41-5", "Srpska književnost (Govornistvo. Govori. Propovedi. Posvete. Predavanja)"},
            {"821.163.41-7", "Srpska književnost (Satire. Humoreske)"},
            {"821.163.41-8", "Srpska književnost (Mesovito)"},
            {"821.163.41-82", "Srpska književnost (Poligrafije. Antologije)"},
            {"821.163.41-83", "Srpska književnost (Rasprave o razlicitim temama)"},
            {"821.163.41-84", "Srpska književnost (Izreke. Aforizmi. Poslovice)"},
            {"821.163.41-92", "Srpska književnost (Periodicna literatura. Polemike. Politicki spisi)"},
            {"821.163.41-93", "Srpska književnost (Knjizevnost za decu i omladinu)"},
            {"821.163.41-94", "Srpska književnost (Istoriografija. Memoari. Dnevnici. Biografije)"},
            {"821.163.41-992", "Srpska književnost (Putopisi)"},
            {"821.163.42", "Hrvatska književnost"},
            {"821.163.6", "Slovenačka književnost"},
            {"821.163.6-93", "Slovenačka dečja književnost (uključujući studije)"},
            {"821.163.6.09", "Slovenačka književnost (studije)"},
            {"821.21/.41", "Orijentalne književnosti. Semitske književnosti (uključujući studije)"},
            {"821.42/.45", "Afričke književnosti (uključujući studije)"},
            {"821.51/.71", "Uralo-altajske književnosti. Azijske književnosti (uključujući studije)"},
            {"821.511.141", "Mađarska književnost (uključujući studije)"},
            {"821.81/.82", "Indijanske književnosti"},
            {"821.81/.87", "Indijanske književnosti (uključujući studije)"},
            {"82:111.852", "Književna estetika"},
            {"902", "Arheologija, teorija"},
            {"902/904", "Arheologija"},
            {"903/904", "Praistorija. Arheološka nalazišta. Kulturni ostaci istorijskog doba"},
            {"908", "Proučavanje zona, lokaliteta"},
            {"908(4)", "Evropske države, proučavanje zavičaja"},
            {"908(497.11)", "Srbija, proučavanje zavičaja"},
            {"908(497.16)", "Crna Gora, proučavanje zavičaja"},
            {"908(5/9)", "Neevropske države, proučavanje zavičaja"},
            {"91", "Geografija"},
            {"910.1", "Geografija. Regionalna geografija"},
            {"911", "Opšta geografija. Sistematska geografija. Teorijska geografija"},
            {"912", "Grafički prikazi određenih područja. Geografske karte. Atlasi. Globusi"},
            {"913", "Regionalna geografija uopšte. Geografija starog i modernog sveta"},
            {"913(100)", "Regionalna geografija sveta"},
            {"913(4)", "Evropske države, geografija"},
            {"913(497.11)", "Srbija, geografija"},
            {"913(497.16)", "Crna Gora, geografija"},
            {"913(5/9)", "Neevropske države, geografija"},
            {"929", "Pojedinačne biografije. Zbirne biografije"},
            {"929.5", "Genealogija"},
            {"929.6/.9", "Heraldika. Biografije. Odlikovanja. Zastave"},
            {"93/94", "Istorija"},
            {"930", "Istorija, teorija"},
            {"930.2", "Pomoćne istorijske nauke. Diplomatika. Epigrafika"},
            {"930.25", "Arhivistika. Arhivi"},
            {"930.85", "Kulturna istorija. Istorija civilizacije"},
            {"94(100)", "Svetska istorija"},
            {"94(100)'.../04\"", "Svetska istorija, stari vek"},
            {"94(100)'04/18\"", "Svetska istorija, srednji i novi vek"},
            {"94(100)\"19\"", "Svetska istorija, 20. v."},
            {"94(100)\"1914/19\"", "Svetski rat 1914-1919"},
            {"94(100)\"1939/45\"", "Svetski rat 1939-1945"},
            {"94(3)", "Antičke države, istorija"},
            {"94(37)", "Antički Rim, istorija"},
            {"94(38)", "Antička Grčka, istorija"},
            {"94(4)", "Evropa, istorija"},
            {"94(4)\"1492/1914", "Evropa, novi vek (1492-1914)"},
            {"94(4)\"19\"", "Evropa, 20. v."},
            {"94(4)\"375/1492\"", "Evropa, srednji vek (ca. 375-1492)"},
            {"94(41/49)", "Evropske države, istorija"},
            {"94(497.1)", "Jugoslavija, istorija (do 1991)"},
            {"94(497.11)", "Srbija, istorija"},
            {"94(497.16)", "Crna Gora, istorija"},
            {"94(5/9)", "Neevropske države, istorija"},
            {"fik", "fiktivni kod"}
        };

        public static RECNIK OsnovniTipovi {
			get {
				RECNIK recnik = new RECNIK();
            	foreach(var oznaka in UDK.UDK_Lista.Keys) if (oznaka.Length == 1 || oznaka.Contains("821.163.41")) recnik.Add(oznaka, UDK.UDK_Lista[oznaka]);
            	return recnik;
			}
        }
		
		public static void PopuniAccentIzbornoPolje(AccentIzbornoPolje lista) {
            lista.Items.Clear();
			switch (Podesavanja.koriscenjeUDK) {
				case UDK_Koriscenje.Nista:
					foreach (STR tip in Enum.GetNames(typeof(EZanrKnjiga))) lista.Items.Add(tip);
					break;
				case UDK_Koriscenje.Osnovno:
					RECNIK osnovno = UDK.OsnovniTipovi;
					foreach (STR i in osnovno.Keys) lista.Items.Add(i + " - " + osnovno[i]);
					break;
				case UDK_Koriscenje.Sve:
					foreach (STR i in UDK.UDK_Lista.Keys) lista.Items.Add(i + " - " + UDK.UDK_Lista[i]);
					break;
				default:
					// System.Diagnostics.Debug.WriteLine("Грешка.");
					break;
			}
		}
    }
}